        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      reset ; Reset               ; Int 08h (IRQ 0)
        dd      tick ; Tick                ; Int 09h (IRQ 1)
        dd      keypress ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      gameOver ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      newPiece ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      received ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      touchdown ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      clear ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84
CPU	8086
align	2

reset:

    push bp
    mov bp, sp
    call resetHandler


tick:

    ;Save context
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    call YKEnterISR

    ;Enable interrupts
    sti
    call tickHandler
    cli
    call signalEOI

    call YKExitISR

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret

keypress:

    ;Save context
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds
    ;Enable interrupts
    call YKEnterISR
    sti
    call keypressHandler
    cli
    call signalEOI
    call YKExitISR

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret

gameOver:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret
    
newPiece:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret
received:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret 
touchdown:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret
clear:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    
    iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
tickCount:
	DW	1
L_myinth_1:
	DW	0
	ALIGN	2
resetHandler:
	; >>>>> Line:	15
	; >>>>> void resetHandler(){ 
	jmp	L_myinth_2
L_myinth_3:
	; >>>>> Line:	17
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_2:
	push	bp
	mov	bp, sp
	jmp	L_myinth_3
	ALIGN	2
L_myinth_5:
	DW	0
L_myinth_6:
	DW	0
	ALIGN	2
tickHandler:
	; >>>>> Line:	20
	; >>>>> void tickHandler(){ 
	jmp	L_myinth_7
L_myinth_8:
	; >>>>> Line:	26
	; >>>>> data = (data + 89) % 100; 
	mov	ax, word [L_myinth_6]
	add	ax, 89
	cwd
	mov	cx, 100
	idiv	cx
	mov	ax, dx
	mov	word [L_myinth_6], ax
	; >>>>> Line:	41
	; >>>>> YKTickHandler(); 
	call	YKTickHandler
	mov	sp, bp
	pop	bp
	ret
L_myinth_7:
	push	bp
	mov	bp, sp
	jmp	L_myinth_8
	ALIGN	2
loopLikeABoss:
	; >>>>> Line:	44
	; >>>>> void loopLikeABoss(){ 
	jmp	L_myinth_10
L_myinth_11:
	; >>>>> Line:	46
	; >>>>> for(; i < 5001; i++){ 
	mov	word [bp-2], 0
	; >>>>> Line:	46
	; >>>>> for(; i < 5001; i++){ 
	jmp	L_myinth_13
L_myinth_12:
	; >>>>> Line:	47
	; >>>>> someLocalVariable++; 
	inc	word [L_myinth_1]
L_myinth_15:
	inc	word [bp-2]
L_myinth_13:
	cmp	word [bp-2], 5001
	jl	L_myinth_12
L_myinth_14:
	mov	sp, bp
	pop	bp
	ret
L_myinth_10:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_11
	ALIGN	2
keypressHandler:
	; >>>>> Line:	51
	; >>>>> void keypressHandler(){ 
	jmp	L_myinth_17
L_myinth_18:
	; >>>>> Line:	54
	; >>>>> c = KeyBuffer; 
	mov	al, byte [KeyBuffer]
	mov	byte [bp-1], al
	mov	sp, bp
	pop	bp
	ret
L_myinth_17:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_18

YKEnterMutex:
    cli
    ret
    
YKExitMutex:
    sti
    ret
    
contextSaver:
    pushf ; Flags
    push cs
    push word[bp+2] ; IP
    
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    mov bx, [saveContextTask]
    mov [bx], sp

    jmp contextRestorer

YKDispatcher: ; Dispatches the next task, and saves context if necessary.
    push bp					
	mov bp, sp
	push ax
	mov ax, word[bp+4]
	cmp	al, 1
	pop ax
	je 	contextSaver

contextRestorer:   
    mov bx, [taskToRun]
    mov sp, [bx]

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax

    iret; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKCtxSwCount:
	DW	0
YKIdleCount:
	DW	0
YKISRCallDepth:
	DW	0
YKTickNum:
	DW	1
currentTask:
	DW	0
saveContextTask:
	DW	0
running:
	DB	0
	ALIGN	2
TCBi:
	DW	0
semi:
	DW	0
Qi:
	DW	0
eventIndex:
	DW	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	50
	; >>>>> void YKInitialize(){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	51
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	54
	; >>>>> YKNewTask(YKIdleTask,(void*)&YKIdleTasks[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (YKIdleTasks+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	jmp	L_yakc_2
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	61
	; >>>>> void YKIdleTask(void){ 
	jmp	L_yakc_4
L_yakc_5:
	; >>>>> Line:	63
	; >>>>> while(1){ 
	jmp	L_yakc_7
L_yakc_6:
	; >>>>> Line:	66
	; >>>>> ackPointer[10] 
	call	YKEnterMutex
	; >>>>> Line:	67
	; >>>>> YKIdleCount++; 
	inc	word [YKIdleCount]
	; >>>>> Line:	69
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_7:
	jmp	L_yakc_6
L_yakc_8:
	mov	sp, bp
	pop	bp
	ret
L_yakc_4:
	push	bp
	mov	bp, sp
	jmp	L_yakc_5
	ALIGN	2
YKNewTask:
	; >>>>> Line:	73
	; >>>>> void YKNewTask(void (*task)(void), void* taskStack, unsigned char priority){ 
	jmp	L_yakc_10
L_yakc_11:
	; >>>>> Line:	77
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	78
	; >>>>> YKTCBs[TCBi].state = 1; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, ax
	add	si, 2
	mov	byte [si], 1
	; >>>>> Line:	79
	; >>>>> YKTCBs[TCBi].priority = priority; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, ax
	add	si, 3
	mov	al, byte [bp+8]
	mov	byte [si], al
	; >>>>> Line:	80
	; >>>>> YKTCBs[TCBi].delay = 0; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	82
	; >>>>> newStackPointer = (unsigned*)taskStack - 11; 
	mov	ax, word [bp+6]
	sub	ax, 22
	mov	word [bp-2], ax
	; >>>>> Line:	84
	; >>>>> for(i = 0; i < 8; i++){ 
	mov	word [bp-4], 0
	jmp	L_yakc_13
L_yakc_12:
	; >>>>> Line:	85
	; >>>>> newStackPointer[i] = 0; 
	mov	ax, word [bp-4]
	shl	ax, 1
	mov	si, ax
	add	si, word [bp-2]
	mov	word [si], 0
L_yakc_15:
	inc	word [bp-4]
L_yakc_13:
	cmp	word [bp-4], 8
	jl	L_yakc_12
L_yakc_14:
	; >>>>> Line:	88
	; >>>>> newStackPointer[8] = (unsigned) task; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	89
	; >>>>> newStackPointer[9] = 0; 
	mov	si, word [bp-2]
	add	si, 18
	mov	word [si], 0
	; >>>>> Line:	90
	; >>>>> newStackPointer[10] 
	mov	si, word [bp-2]
	add	si, 20
	mov	word [si], 512
	; >>>>> Line:	93
	; >>>>> YKTCBs[TCBi].stackPtr = newStackPointer - 1; 
	mov	ax, word [bp-2]
	sub	ax, 2
	push	ax
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	mov	dx, ax
	mov	si, dx
	add	si, YKTCBs
	pop	ax
	mov	word [si], ax
	; >>>>> Line:	95
	; >>>>> if(TCBi == 0){ 
	mov	ax, word [TCBi]
	test	ax, ax
	jne	L_yakc_16
	; >>>>> Line:	96
	; >>>>> readyRoot = &YKTCBs[TCBi]; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	word [readyRoot], ax
	; >>>>> Line:	97
	; >>>>> YKTCBs[TCBi].next = 0; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, ax
	add	si, 4
	mov	word [si], 0
	jmp	L_yakc_17
L_yakc_16:
	; >>>>> Line:	99
	; >>>>> if(priority < readyRoot->priority){ 
	mov	si, word [readyRoot]
	add	si, 3
	mov	al, byte [bp+8]
	cmp	al, byte [si]
	jae	L_yakc_18
	; >>>>> Line:	100
	; >>>>> YKTCBs[TCBi].next = readyRoot; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, ax
	add	si, 4
	mov	ax, word [readyRoot]
	mov	word [si], ax
	; >>>>> Line:	101
	; >>>>> readyRoot = &YKTCBs[TCBi]; 
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	word [readyRoot], ax
	jmp	L_yakc_19
L_yakc_18:
	; >>>>> Line:	104
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-6], ax
	; >>>>> Line:	106
	; >>>>> while(browser){ 
	jmp	L_yakc_21
L_yakc_20:
	; >>>>> Line:	107
	; >>>>> if(priority < browser->next->priority){ 
	mov	si, word [bp-6]
	add	si, 4
	mov	si, word [si]
	add	si, 3
	mov	al, byte [bp+8]
	cmp	al, byte [si]
	jae	L_yakc_23
	; >>>>> Line:	108
	; >>>>> YKTCBs[TCBi].next = browser->next; 
	mov	si, word [bp-6]
	add	si, 4
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	di, ax
	add	di, 4
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	109
	; >>>>> oRun  
	mov	ax, word [TCBi]
	mov	cx, 18
	imul	cx
	add	ax, YKTCBs
	mov	si, word [bp-6]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	110
	; >>>>> break; 
	jmp	L_yakc_22
L_yakc_23:
	; >>>>> Line:	112
	; >>>>> browser = browser->next; 
	mov	si, word [bp-6]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_21:
	mov	ax, word [bp-6]
	test	ax, ax
	jne	L_yakc_20
L_yakc_22:
L_yakc_19:
L_yakc_17:
	; >>>>> Line:	117
	; >>>>> TCBi++; 
	inc	word [TCBi]
	; >>>>> Line:	118
	; >>>>> if(running){ 
	mov	al, byte [running]
	test	al, al
	je	L_yakc_24
	; >>>>> Line:	119
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_24:
	mov	sp, bp
	pop	bp
	ret
L_yakc_10:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_11
	ALIGN	2
YKScheduler:
	; >>>>> Line:	123
	; >>>>> void YKScheduler(unsigned char saveContext){ 
	jmp	L_yakc_26
L_yakc_27:
	; >>>>> Line:	126
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-2], ax
	; >>>>> Line:	127
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	128
	; >>>>> while(browser){ 
	jmp	L_yakc_29
L_yakc_28:
	; >>>>> Line:	129
	; >>>>> if(browser->state == 1){ 
	mov	si, word [bp-2]
	add	si, 2
	cmp	byte [si], 1
	jne	L_yakc_31
	; >>>>> Line:	130
	; >>>>> taskToRun = browser; 
	mov	ax, word [bp-2]
	mov	word [taskToRun], ax
	; >>>>> Line:	131
	; >>>>> break; 
	jmp	L_yakc_30
L_yakc_31:
	; >>>>> Line:	133
	; >>>>> browser = browser->next; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_29:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_28
L_yakc_30:
	; >>>>> Line:	136
	; >>>>> if(taskToRun  
	mov	ax, word [currentTask]
	cmp	ax, word [taskToRun]
	je	L_yakc_32
	; >>>>> Line:	138
	; >>>>> saveContextTask = currentTask; 
	mov	ax, word [currentTask]
	mov	word [saveContextTask], ax
	; >>>>> Line:	139
	; >>>>> currentTask = taskToRun; 
	mov	ax, word [taskToRun]
	mov	word [currentTask], ax
	; >>>>> Line:	142
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	143
	; >>>>> YKDispatcher(saveContext); 
	push	word [bp+4]
	call	YKDispatcher
	add	sp, 2
L_yakc_32:
	mov	sp, bp
	pop	bp
	ret
L_yakc_26:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_27
	ALIGN	2
YKRun:
	; >>>>> Line:	148
	; >>>>> void YKRun() { 
	jmp	L_yakc_34
L_yakc_35:
	; >>>>> Line:	150
	; >>>>> running = 1; 
	mov	byte [running], 1
	; >>>>> Line:	151
	; >>>>> YKScheduler(0); 
	xor	al, al
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_34:
	push	bp
	mov	bp, sp
	jmp	L_yakc_35
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	154
	; >>>>> void YKDelayTask(unsigned count){ 
	jmp	L_yakc_37
L_yakc_38:
	; >>>>> Line:	156
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	158
	; >>>>> if(!count){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_39
	; >>>>> Line:	160
	; >>>>> return; 
	jmp	L_yakc_40
	jmp	L_yakc_41
L_yakc_39:
	; >>>>> Line:	164
	; >>>>> currentTask->delay = count; 
	mov	si, word [currentTask]
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	165
	; >>>>> currentTask->state = 0; 
	mov	si, word [currentTask]
	add	si, 2
	mov	byte [si], 0
	; >>>>> Line:	167
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	168
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_41:
L_yakc_40:
	mov	sp, bp
	pop	bp
	ret
L_yakc_37:
	push	bp
	mov	bp, sp
	jmp	L_yakc_38
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	173
	; >>>>> void YKEnterISR(void){ 
	jmp	L_yakc_43
L_yakc_44:
	; >>>>> Line:	175
	; >>>>> YKISRCallDepth++; 
	inc	word [YKISRCallDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_43:
	push	bp
	mov	bp, sp
	jmp	L_yakc_44
	ALIGN	2
YKExitISR:
	; >>>>> Line:	178
	; >>>>> < 0){ 
	jmp	L_yakc_46
L_yakc_47:
	; >>>>> Line:	179
	; >>>>> YKISRCallDepth--; 
	dec	word [YKISRCallDepth]
	; >>>>> Line:	182
	; >>>>> if(!YKISRCallDepth){ 
	mov	ax, word [YKISRCallDepth]
	test	ax, ax
	jne	L_yakc_48
	; >>>>> Line:	183
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	184
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_48:
	mov	sp, bp
	pop	bp
	ret
L_yakc_46:
	push	bp
	mov	bp, sp
	jmp	L_yakc_47
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	188
	; >>>>> void YKTickHandler(void){ 
	jmp	L_yakc_50
L_yakc_51:
	; >>>>> Line:	192
	; >>>>> YKTickNum++; 
	inc	word [YKTickNum]
	; >>>>> Line:	194
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-2], ax
	; >>>>> Line:	195
	; >>>>> while(browser){ 
	jmp	L_yakc_53
L_yakc_52:
	; >>>>> Line:	196
	; >>>>> if(browser->state == 0){ 
	mov	si, word [bp-2]
	add	si, 2
	mov	al, byte [si]
	test	al, al
	jne	L_yakc_55
	; >>>>> Line:	197
	; >>>>> browser->delay--; 
	mov	si, word [bp-2]
	add	si, 6
	dec	word [si]
	; >>>>> Line:	203
	; >>>>> if(!(browser->delay)){ 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_56
	; >>>>> Line:	204
	; >>>>> browser->state = 1; 
	mov	si, word [bp-2]
	add	si, 2
	mov	byte [si], 1
L_yakc_56:
L_yakc_55:
	; >>>>> Line:	209
	; >>>>> browser = browser->next; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_53:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_52
L_yakc_54:
	mov	sp, bp
	pop	bp
	ret
L_yakc_50:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_51
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	213
	; >>>>> YKSem* YKSemCreate(int val){ 
	jmp	L_yakc_58
L_yakc_59:
	; >>>>> Line:	215
	; >>>>> if(val < 0){ 
	cmp	word [bp+4], 0
	jge	L_yakc_60
	; >>>>> Line:	216
	; >>>>> return  
	xor	ax, ax
	jmp	L_yakc_61
L_yakc_60:
	; >>>>> Line:	219
	; >>>>> newSem = &YKSEMS[semi]; 
	mov	ax, word [semi]
	shl	ax, 1
	add	ax, YKSEMS
	mov	word [bp-2], ax
	; >>>>> Line:	220
	; >>>>> *newSem = val; 
	mov	si, word [bp-2]
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	221
	; >>>>> semi++; 
	inc	word [semi]
	; >>>>> Line:	222
	; >>>>> return newSem; 
	mov	ax, word [bp-2]
L_yakc_61:
	mov	sp, bp
	pop	bp
	ret
L_yakc_58:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_59
	ALIGN	2
YKSemPend:
	; >>>>> Line:	225
	; >>>>> void YKSemPend(YKSem* sem){ 
	jmp	L_yakc_63
L_yakc_64:
	; >>>>> Line:	226
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	227
	; >>>>> if(!(*sem)){ 
	mov	si, word [bp+4]
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_65
	; >>>>> Line:	228
	; >>>>> currentTask->state = 2; 
	mov	si, word [currentTask]
	add	si, 2
	mov	byte [si], 2
	; >>>>> Line:	229
	; >>>>> currentTask->semBlock = sem; 
	mov	si, word [currentTask]
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	230
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_65:
	; >>>>> Line:	232
	; >>>>> (*sem)--; 
	mov	si, word [bp+4]
	dec	word [si]
	; >>>>> Line:	233
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_63:
	push	bp
	mov	bp, sp
	jmp	L_yakc_64
	ALIGN	2
YKSemPost:
	; >>>>> Line:	237
	; >>>>> void YKSemPost(YKSem* sem){ 
	jmp	L_yakc_67
L_yakc_68:
	; >>>>> Line:	240
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	241
	; >>>>> (*sem)++; 
	mov	si, word [bp+4]
	inc	word [si]
	; >>>>> Line:	242
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-2], ax
	; >>>>> Line:	244
	; >>>>> while(browser){ 
	jmp	L_yakc_70
L_yakc_69:
	; >>>>> Line:	245
	; >>>>> if(browser->state == 2 && browser->semBlock == sem){ 
	mov	si, word [bp-2]
	add	si, 2
	cmp	byte [si], 2
	jne	L_yakc_72
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_72
	; >>>>> Line:	246
	; >>>>> browser-> 
	mov	si, word [bp-2]
	add	si, 2
	mov	byte [si], 1
	; >>>>> Line:	247
	; >>>>> browser->semBlock = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	248
	; >>>>> break; 
	jmp	L_yakc_71
L_yakc_72:
	; >>>>> Line:	250
	; >>>>> browser = browser->next; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_70:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_69
L_yakc_71:
	; >>>>> Line:	253
	; >>>>> if(YKISRCallDepth == 0){ 
	mov	ax, word [YKISRCallDepth]
	test	ax, ax
	jne	L_yakc_73
	; >>>>> Line:	254
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_73:
	; >>>>> Line:	256
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_67:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_68
	ALIGN	2
YKQCreate:
	; >>>>> Line:	259
	; >>>>> YKQ* YKQCreate(void** start, unsigned size){ 
	jmp	L_yakc_75
L_yakc_76:
	; >>>>> Line:	260
	; >>>>> YKQS[Qi].length = size; 
	mov	ax, word [Qi]
	mov	cx, 10
	imul	cx
	add	ax, YKQS
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	261
	; >>>>> YKQS[Qi].queueAddress = start; 
	mov	ax, word [Qi]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQS
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	262
	; >>>>> YKQS[Qi].nextEmpty = start; 
	mov	ax, word [Qi]
	mov	cx, 10
	imul	cx
	add	ax, YKQS
	mov	si, ax
	add	si, 4
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	263
	; >>>>> YKQS[Qi].nextRemove = start; 
	mov	ax, word [Qi]
	mov	cx, 10
	imul	cx
	add	ax, YKQS
	mov	si, ax
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	264
	; >>>>> YKQS[Qi].state = 0; 
	mov	ax, word [Qi]
	mov	cx, 10
	imul	cx
	add	ax, YKQS
	mov	si, ax
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	266
	; >>>>> Qi++; 
	inc	word [Qi]
	; >>>>> Line:	268
	; >>>>> return &YKQS[Qi - 1]; 
	mov	ax, word [Qi]
	dec	ax
	mov	cx, 10
	imul	cx
	add	ax, YKQS
L_yakc_77:
	mov	sp, bp
	pop	bp
	ret
L_yakc_75:
	push	bp
	mov	bp, sp
	jmp	L_yakc_76
	ALIGN	2
YKQPend:
	; >>>>> Line:	271
	; >>>>> void* YKQPend(YKQ* q){ 
	jmp	L_yakc_79
L_yakc_80:
	; >>>>> Line:	273
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	274
	; >>>>> if(q->stat 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_81
	; >>>>> Line:	275
	; >>>>> currentTask->state = 3; 
	mov	si, word [currentTask]
	add	si, 2
	mov	byte [si], 3
	; >>>>> Line:	276
	; >>>>> currentTask->qBlock = q; 
	mov	si, word [currentTask]
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	277
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_81:
	; >>>>> Line:	280
	; >>>>> t = (void*)* q->nextRemove; 
	mov	si, word [bp+4]
	add	si, 6
	mov	si, word [si]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	281
	; >>>>> q->nextRemove++; 
	mov	si, word [bp+4]
	add	si, 6
	add	word [si], 2
	; >>>>> Line:	283
	; >>>>> if(q->nextRemove == q->queueAddress + q->length){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	shl	ax, 1
	mov	si, word [bp+4]
	add	ax, word [si]
	add	si, 6
	mov	dx, word [si]
	cmp	dx, ax
	jne	L_yakc_82
	; >>>>> Line:	284
	; >>>>> q->nextRemove = q->queueAddress; 
	mov	si, word [bp+4]
	mov	di, word [bp+4]
	add	di, 6
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_82:
	; >>>>> Line:	287
	; >>>>> if(q->state == 1){ 
	mov	si, word [bp+4]
	add	si, 8
	cmp	word [si], 1
	jne	L_yakc_83
	; >>>>> Line:	288
	; >>>>> q->state = 2; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
	jmp	L_yakc_84
L_yakc_83:
	; >>>>> Line:	289
	; >>>>> } else if(q->nextRemove == q->nextEmpty){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jne	L_yakc_85
	; >>>>> Line:	290
	; >>>>> q->state = 0; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 0
L_yakc_85:
L_yakc_84:
	; >>>>> Line:	292
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	293
	; >>>>> return t; 
	mov	ax, word [bp-2]
L_yakc_86:
	mov	sp, bp
	pop	bp
	ret
L_yakc_79:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_80
	ALIGN	2
YKQPost:
	; >>>>> Line:	296
	; >>>>> int YKQPost(YKQ* q, void* msg){ 
	jmp	L_yakc_88
L_yakc_89:
	; >>>>> Line:	298
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	300
	; >>>>> if(q->state == 
	mov	si, word [bp+4]
	add	si, 8
	cmp	word [si], 1
	jne	L_yakc_90
	; >>>>> Line:	301
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	302
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_yakc_91
L_yakc_90:
	; >>>>> Line:	305
	; >>>>> *(q->nextEmpty) = msg; 
	mov	si, word [bp+4]
	add	si, 4
	mov	si, word [si]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	306
	; >>>>> q->nextEmpty++; 
	mov	si, word [bp+4]
	add	si, 4
	add	word [si], 2
	; >>>>> Line:	308
	; >>>>> if(q->nextEmpty == q->queueAddress + q->length){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	shl	ax, 1
	mov	si, word [bp+4]
	add	ax, word [si]
	add	si, 4
	mov	dx, word [si]
	cmp	dx, ax
	jne	L_yakc_92
	; >>>>> Line:	309
	; >>>>> q->nextEmpty = q->queueAddress; 
	mov	si, word [bp+4]
	mov	di, word [bp+4]
	add	di, 4
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_92:
	; >>>>> Line:	312
	; >>>>> if(q->state == 0){ 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_93
	; >>>>> Line:	313
	; >>>>> q->state = 2; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
	jmp	L_yakc_94
L_yakc_93:
	; >>>>> Line:	314
	; >>>>> } else if(q->nextRemove == q->nextEmpty){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jne	L_yakc_95
	; >>>>> Line:	315
	; >>>>> q->state = 1; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 1
L_yakc_95:
L_yakc_94:
	; >>>>> Line:	317
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-2], ax
	; >>>>> Line:	319
	; >>>>> while(browser){ 
	jmp	L_yakc_97
L_yakc_96:
	; >>>>> Line:	320
	; >>>>> if(browser->state == 3){ 
	mov	si, word [bp-2]
	add	si, 2
	cmp	byte [si], 3
	jne	L_yakc_99
	; >>>>> Line:	321
	; >>>>> if(browser->qBlock == q){ 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_100
	; >>>>> Line:	322
	; >>>>> browser->state = 1; 
	mov	si, word [bp-2]
	add	si, 2
	mov	byte [si], 1
	; >>>>> Line:	323
	; >>>>> browser->qBlock = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	324
	; >>>>> f( 
	jmp	L_yakc_98
L_yakc_100:
L_yakc_99:
	; >>>>> Line:	327
	; >>>>> browser = browser->next; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	328
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_97:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_96
L_yakc_98:
	; >>>>> Line:	331
	; >>>>> if(YKISRCallDepth == 0){ 
	mov	ax, word [YKISRCallDepth]
	test	ax, ax
	jne	L_yakc_101
	; >>>>> Line:	332
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_101:
	; >>>>> Line:	335
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	336
	; >>>>> return 1; 
	mov	ax, 1
L_yakc_91:
	mov	sp, bp
	pop	bp
	ret
L_yakc_88:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_89
	ALIGN	2
YKEventCreate:
	; >>>>> Line:	348
	; >>>>> YKEVENT *YKEventCreate(unsigned initialValue) { 
	jmp	L_yakc_103
L_yakc_104:
	; >>>>> Line:	349
	; >>>>> YKEvents[eventIndex].flag = initialValue; 
	mov	ax, word [eventIndex]
	shl	ax, 1
	mov	si, ax
	add	si, YKEvents
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	350
	; >>>>> eventIndex++; 
	inc	word [eventIndex]
	; >>>>> Line:	352
	; >>>>> return &YKEvents[eventIndex-1]; 
	mov	ax, word [eventIndex]
	dec	ax
	shl	ax, 1
	add	ax, YKEvents
L_yakc_105:
	mov	sp, bp
	pop	bp
	ret
L_yakc_103:
	push	bp
	mov	bp, sp
	jmp	L_yakc_104
	ALIGN	2
YKEventPend:
	; >>>>> Line:	367
	; >>>>> unsigned YKEventPend(YKEVENT *event, unsigned eventMask, int waitMode) { 
	jmp	L_yakc_107
L_yakc_108:
	; >>>>> Line:	368
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	370
	; >>>>> if(waitMode == 2){ 
	cmp	word [bp+8], 2
	jne	L_yakc_109
	; >>>>> Line:	371
	; >>>>> if( 
	mov	si, word [bp+4]
	mov	ax, word [bp+6]
	cmp	ax, word [si]
	jne	L_yakc_110
	; >>>>> Line:	372
	; >>>>> return event->flag; 
	mov	ax, word [si]
	jmp	L_yakc_111
L_yakc_110:
	jmp	L_yakc_112
L_yakc_109:
	; >>>>> Line:	375
	; >>>>> else if(waitMode == 1){ 
	cmp	word [bp+8], 1
	jne	L_yakc_113
	; >>>>> Line:	376
	; >>>>> if(event->flag & eventMask){ 
	mov	si, word [bp+4]
	mov	ax, word [si]
	and	ax, word [bp+6]
	je	L_yakc_114
	; >>>>> Line:	377
	; >>>>> return event->flag; 
	mov	ax, word [si]
	jmp	L_yakc_111
L_yakc_114:
L_yakc_113:
L_yakc_112:
	; >>>>> Line:	381
	; >>>>> currentTask->event = event; 
	mov	si, word [currentTask]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	382
	; >>>>> currentTask->mask = eventMask; 
	mov	si, word [currentTask]
	add	si, 16
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	383
	; >>>>> currentTask->mode = waitMode; 
	mov	si, word [currentTask]
	add	si, 14
	mov	ax, word [bp+8]
	mov	word [si], ax
	; >>>>> Line:	384
	; >>>>> currentTask->state = 5; 
	mov	si, word [currentTask]
	add	si, 2
	mov	byte [si], 5
	; >>>>> Line:	386
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	388
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	389
	; >>>>> return event->flag; 
	mov	si, word [bp+4]
	mov	ax, word [si]
L_yakc_111:
	mov	sp, bp
	pop	bp
	ret
L_yakc_107:
	push	bp
	mov	bp, sp
	jmp	L_yakc_108
L_yakc_117:
	DB	"ANY",0
L_yakc_116:
	DB	"ALL",0
	ALIGN	2
YKEventSet:
	; >>>>> Line:	399
	; >>>>> void YKEventSet(YKEVENT *event, unsigned eventMask) { 
	jmp	L_yakc_118
L_yakc_119:
	; >>>>> Line:	401
	; >>>>> event->flag = event->flag |  
	mov	si, word [bp+4]
	mov	ax, word [si]
	or	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	403
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	405
	; >>>>> browser = readyRoot; 
	mov	ax, word [readyRoot]
	mov	word [bp-2], ax
	; >>>>> Line:	406
	; >>>>> while(browser){ 
	jmp	L_yakc_121
L_yakc_120:
	; >>>>> Line:	407
	; >>>>> if ((browser->state == 5) && (browser->event == event)) { 
	mov	si, word [bp-2]
	add	si, 2
	cmp	byte [si], 5
	jne	L_yakc_123
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_123
	; >>>>> Line:	408
	; >>>>> if(browser->mode == 2){ 
	mov	si, word [bp-2]
	add	si, 14
	cmp	word [si], 2
	jne	L_yakc_124
	; >>>>> Line:	409
	; >>>>> if(event->flag == browser->mask){ 
	mov	si, word [bp-2]
	add	si, 16
	mov	di, word [bp+4]
	mov	ax, word [di]
	cmp	ax, word [si]
	jne	L_yakc_125
	; >>>>> Line:	410
	; >>>>> printString("ALL"); 
	mov	ax, L_yakc_116
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	411
	; >>>>> browser->state = 1; 
	mov	si, word [bp-2]
	add	si, 2
	mov	byte [si], 1
	; >>>>> Line:	412
	; >>>>> browser->event = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	413
	; >>>>> browser->mask = 0; 
	mov	si, word [bp-2]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	414
	; >>>>> browser->mode = 0; 
	mov	si, word [bp-2]
	add	si, 14
	mov	word [si], 0
L_yakc_125:
	jmp	L_yakc_126
L_yakc_124:
	; >>>>> Line:	417
	; >>>>> else if(browser->mode == 1){ 
	mov	si, word [bp-2]
	add	si, 14
	cmp	word [si], 1
	jne	L_yakc_127
	; >>>>> Line:	418
	; >>>>> nt->flag &  
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [si]
	mov	si, word [bp+4]
	and	ax, word [si]
	je	L_yakc_128
	; >>>>> Line:	419
	; >>>>> printString("ANY"); 
	mov	ax, L_yakc_117
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	420
	; >>>>> browser->state = 1; 
	mov	si, word [bp-2]
	add	si, 2
	mov	byte [si], 1
	; >>>>> Line:	421
	; >>>>> browser->event = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	422
	; >>>>> browser->mask = 0; 
	mov	si, word [bp-2]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	423
	; >>>>> browser->mode = 0; 
	mov	si, word [bp-2]
	add	si, 14
	mov	word [si], 0
L_yakc_128:
L_yakc_127:
L_yakc_126:
L_yakc_123:
	; >>>>> Line:	428
	; >>>>> browser = browser->next; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	429
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_121:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_120
L_yakc_122:
	; >>>>> Line:	432
	; >>>>> if(YKISRCallDepth == 0){ 
	mov	ax, word [YKISRCallDepth]
	test	ax, ax
	jne	L_yakc_129
	; >>>>> Line:	433
	; >>>>> YKScheduler(1); 
	mov	al, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_129:
	; >>>>> Line:	436
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_118:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_119
	ALIGN	2
YKEventReset:
	; >>>>> Line:	439
	; >>>>> void YKEventReset(YKEVENT *event, unsigned eventMask) { 
	jmp	L_yakc_131
L_yakc_132:
	; >>>>> Line:	440
	; >>>>> event->flag = event->flag &  
	mov	ax, word [bp+6]
	not	ax
	mov	si, word [bp+4]
	and	ax, word [si]
	mov	word [si], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_131:
	push	bp
	mov	bp, sp
	jmp	L_yakc_132
	ALIGN	2
YKTCBs:
	TIMES	180 db 0
YKSEMS:
	TIMES	100 db 0
YKQS:
	TIMES	100 db 0
YKEvents:
	TIMES	100 db 0
readyRoot:
	TIMES	2 db 0
taskToRun:
	TIMES	2 db 0
YKIdleTasks:
	TIMES	512 db 0
; Generated by c86 (BYU-NASM) 5.1 (beta) from simptrisApp.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
seed:
	DD	37428
L_simptrisApp_1:
	DB	"You made it",0xA,0
	ALIGN	2
STask:
	; >>>>> Line:	11
	; >>>>> void STask() { 
	jmp	L_simptrisApp_2
L_simptrisApp_3:
	; >>>>> Line:	12
	; >>>>> while(1) { 
	jmp	L_simptrisApp_5
L_simptrisApp_4:
	; >>>>> Line:	13
	; >>>>> YKDelayTask(20); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	14
	; >>>>> printString("You made it\n"); 
	mov	ax, L_simptrisApp_1
	push	ax
	call	printString
	add	sp, 2
L_simptrisApp_5:
	jmp	L_simptrisApp_4
L_simptrisApp_6:
	mov	sp, bp
	pop	bp
	ret
L_simptrisApp_2:
	push	bp
	mov	bp, sp
	jmp	L_simptrisApp_3
	ALIGN	2
main:
	; >>>>> Line:	18
	; >>>>> void main() { 
	jmp	L_simptrisApp_8
L_simptrisApp_9:
	; >>>>> Line:	19
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	24
	; >>>>> YKNewTask(STask, (void *) &STaskStk[512], 10); 
	mov	al, 10
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	26
	; >>>>> StartSimptris(); 
	call	StartSimptris
	; >>>>> Line:	27
	; >>>>> SeedSimptris(seed); 
	push	word [(seed+2)]
	push	word [(seed+0)]
	call	SeedSimptris
	add	sp, 4
	; >>>>> Line:	29
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_simptrisApp_8:
	push	bp
	mov	bp, sp
	jmp	L_simptrisApp_9
	ALIGN	2
STaskStk:
	TIMES	1024 db 0
	align	2
SlidePiece:	; void SlidePiece(int ID, int direction)
	push	bp
	mov	bp, sp
	push	ax
	push	dx
 	mov	ah, 0		; Slide piece operation
  	mov	al, [bp+6]	; Move direction (loword only)
	mov	dx, [bp+4]	; Move id
	int	1Bh		; Call Simptris services
	pop	dx
	pop	ax
	pop	bp
	ret
RotatePiece:	; void RotatePiece(int ID, int direction)
	push	bp
	mov	bp, sp
	push	ax
	push	dx
 	mov	ah, 1		; Rotate piece operation
 	mov	al, [bp+6]	; Move direction (loword only)
	mov	dx, [bp+4]	; Move id
	int	1Bh		; Call Simptris services
	pop	dx
	pop	ax
	pop	bp
	ret
SeedSimptris:	; void SeedSimptris(long seed)
	push	bp
	mov	bp, sp
	push	ax
	push	cx
	push    dx
 	mov	ah, 2		; Seed operation
	mov	dx, [bp+4]	; Move loword of seed
	mov	cx, [bp+6]	; Move hiword of seed
	int	1Bh		; Call Simptris services
	pop	dx
	pop	cx
	pop	ax
	pop	bp
	ret
StartSimptris:	; void StartSimptris(void)
	push	ax
 	mov	ah, 3		; Start Simptris operation
	int	1Bh		; Call Simptris services
	pop	ax
	ret

