; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
ykTasks:
	TIMES	132 db 0
YKSuspList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
currentTaskCount:
	TIMES	2 db 0
YKRunTask:
	TIMES	2 db 0
YKContextSP:
	TIMES	2 db 0
YKRestoreSP:
	TIMES	2 db 0
YKCurrentRunningTask:
	TIMES	2 db 0
YKIdleTaskStack:
	TIMES	512 db 0
readyRoot:
	TIMES	2 db 0
readyTail:
	TIMES	2 db 0
